title: "Yize Xie"
author: "Yize Xie"
description: "Columbia University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Experience", file: "Experience.md"}
  - {title: "Projects", file: "Projects.md"}
  - {title: "CV", url: "https://github.com/alphaB8T/alphab8t.github.io/blob/master/YizeXie_Resume.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yx2784@columbia.edu"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/yize-xie-54307421a/"}
  - {title: GitHub, icon: github, url: "https://github.com/alphaB8T"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
